#!/usr/bin/env python3
"""Generate the trust store the kernel compiles in.

A TLS client has to decide which certificate authorities it believes, and that
decision has to be baked in: there is nothing to fetch it from at boot, and a
store that can be replaced over the network is not a trust store.

What is stored per root is its subject name and its SubjectPublicKeyInfo —
not the whole certificate.  The key is what verifying the last signature in a
chain needs and the name is what finds it; the rest of a root certificate
(validity, extensions, and its own signature) is either irrelevant once the
root is trusted or would cost a third of the kernel's size budget to carry.

Sizes

    A Mozilla bundle root averages about 350 bytes of (subject, SPKI).
    All 121 of them is roughly 42 KiB of DER, which is 85 KiB as hex in the
    source, and this kernel has 23 KiB of headroom under the BIOS loader's
    ceiling.  So the store is either a subset, or the loader has to change.

    --roots picks: "all" for everything, or a comma-separated list of
    substrings matched against each root's subject.

Usage: scripts/gen-truststore.py <cacert.pem> <out.rs> [--roots all|list]
"""

import base64
import io
import os
import re
import sys


def load_roots(pem_path):
    """Every certificate in a PEM bundle, as DER."""
    text = io.open(pem_path, encoding="utf-8", errors="replace").read()
    blocks = re.findall(
        r"-----BEGIN CERTIFICATE-----.*?-----END CERTIFICATE-----", text, re.S
    )
    return [base64.b64decode("".join(b.splitlines()[1:-1])) for b in blocks]


def der_len(d):
    """The length of the value starting at d[1]."""
    b = d[1]
    if b & 0x80:
        n = b & 0x7F
        return 2 + n + int.from_bytes(d[2:2 + n], "big")
    return 2 + b


def fields(cert):
    """(subject DER, SubjectPublicKeyInfo DER, readable name)."""
    from cryptography import x509
    from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat

    c = x509.load_der_x509_certificate(cert)
    # Re-encoded rather than sliced out of the certificate: the SPKI is a
    # field of the TBSCertificate, and re-encoding is what the parser already
    # knows how to do.  It is DER either way.
    spki = c.public_key().public_bytes(Encoding.DER, PublicFormat.SubjectPublicKeyInfo)
    subject = c.subject.public_bytes()
    return subject, spki, c.subject.rfc4514_string()


def rust_bytes(name, data):
    """A &[u8] constant, as hex.

    Hex rather than a byte literal because a byte literal long enough to hold
    a key has to wrap, and a wrapped one silently gains the newline and the
    indentation as bytes.  The hex is decoded once at boot into .bss, which
    costs RAM instead of kernel image size.
    """
    return 'const %s: &[u8] = b"%s";' % (name, data.hex())


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    pem, out = sys.argv[1], sys.argv[2]
    # The list can come from the environment as well as the command line:
    # make hands a comma-separated argument through a shell, and the quoting
    # survives differently on msys than it does here.
    which = os.environ.get("TRUST_ROOTS", "all")
    if "--roots" in sys.argv:
        which = sys.argv[sys.argv.index("--roots") + 1]

    certs = load_roots(pem)
    chosen = []
    for d in certs:
        try:
            subject, spki, name = fields(d)
        except Exception:
            continue
        if which != "all":
            wanted = [w.strip().lower() for w in which.split(",") if w.strip()]
            if not any(w in name.lower() for w in wanted):
                continue
        chosen.append((subject, spki, name))

    if not chosen:
        sys.exit("gen-truststore: no roots matched %r" % which)

    lines = [
        "// Generated by scripts/gen-truststore.py -- do not edit.",
        "//",
        "// Each entry is a root's subject name and its public key, as hex.",
        "// The hex is decoded into the arena below at boot, so the table costs",
        "// RAM rather than kernel image size.",
        "",
        "/// One trusted root, as an offset and length into HEXTAB.",
        "pub struct Root {",
        "    pub subject: &'static [u8],",
        "    pub spki: &'static [u8],",
        "}",
        "",
    ]
    for i, (subject, spki, _) in enumerate(chosen):
        lines.append(rust_bytes("SUBJ_%d" % i, subject))
        lines.append(rust_bytes("SPKI_%d" % i, spki))
    lines.append("")
    lines.append("pub const ROOTS: &[Root] = &[")
    for i, (_, _, name) in enumerate(chosen):
        lines.append('    // %s' % name[:90])
        lines.append("    Root { subject: SUBJ_%d, spki: SPKI_%d }," % (i, i))
    lines.append("];")
    lines.append("")

    text = "\n".join(lines)
    io.open(out, "w", encoding="utf-8", newline="\n").write(text)

    der = sum(len(s) + len(k) for s, k, _ in chosen)
    print("[truststore] %d root(s), %d bytes of DER, %d bytes of source"
          % (len(chosen), der, len(text)))


if __name__ == "__main__":
    main()
