#!/usr/bin/env python3
"""Embed the boot chain into the kernel image.

The installer has to write a working bootloader to the target disk.  Reading it
back off the medium it booted from would only work when that medium is a hard
disk — a CD needs ATAPI, which this kernel does not have.  So the boot chain is
compiled into the kernel instead, and the installer carries it everywhere.

Writes `build/bootimg.rs`, which `main.rs` pulls in with `include!`.  rustc
records included files in its dep-info, so cargo rebuilds when this changes.

stage2 is embedded *unpatched*: its header still says "kernel size 0".  The
installer fills that in with the size of the kernel it is writing, using the
same offset the Makefile patches.
"""

import os
import sys

OUT = os.path.join("build", "bootimg.rs")


def emit_array(f, name, data):
    f.write("pub static %s: [u8; %d] = [\n" % (name, len(data)))
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        f.write("    " + " ".join("0x%02X," % b for b in chunk) + "\n")
    f.write("];\n\n")


def main():
    if len(sys.argv) not in (3, 4):
        sys.exit("usage: gen-bootimg.py <mbr.bin> <stage2.bin> [test.exe]")

    mbr_path, stage2_path = sys.argv[1], sys.argv[2]
    exe_path = sys.argv[3] if len(sys.argv) == 4 else None
    mbr = open(mbr_path, "rb").read()
    stage2 = open(stage2_path, "rb").read()
    exe = open(exe_path, "rb").read() if exe_path else b""

    if len(mbr) != 512:
        sys.exit("gen-bootimg: MBR is %d bytes, expected 512" % len(mbr))
    if len(stage2) < 8 or stage2[0] != 0xEB:
        sys.exit("gen-bootimg: stage2 does not look like a boot image")
    if len(stage2) % 512 != 0:
        sys.exit("gen-bootimg: stage2 is not a whole number of sectors")

    # encoding is explicit: Python on Windows defaults to the system codepage
    # (GBK here), and rustc rejects a source file that is not valid UTF-8 — an
    # em-dash in a comment is enough to break it.
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("// Generated by scripts/gen-bootimg.py — do not edit.\n")
        f.write("// The boot chain, carried inside the kernel so the installer can\n")
        f.write("// write it to a target disk whatever it booted from.\n\n")
        f.write("/// LBA 0 of an installed disk.\n")
        emit_array(f, "MBR", mbr)
        f.write("/// LBA 1..: the loader.  Its kernel-size header is still zero and\n")
        f.write("/// must be filled in by whoever writes it.\n")
        emit_array(f, "STAGE2", stage2)
        if exe:
            f.write("/// A tiny PE32+ program, installed as /bin/hello.exe so the\n")
            f.write("/// loader has something to run without needing a disk first.\n")
            emit_array(f, "TEST_EXE", exe)

    print("[bootimg] embedded MBR (%d B), stage2 (%d B)%s into %s"
          % (len(mbr), len(stage2),
             ", test exe (%d B)" % len(exe) if exe else "",
             OUT))


if __name__ == "__main__":
    main()
